# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cubicle}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nathan Stults"]
  s.date = %q{2010-03-14}
  s.description = %q{Cubicle provides a dsl and aggregation caching framework for automating the generation, execution and caching of map reduce queries when using MongoDB in Ruby. Cubicle also includes a MongoMapper plugin for quickly performing ad-hoc, multi-level group-by queries against a MongoMapper model.}
  s.email = %q{hereiam@sonic.net}
  s.extra_rdoc_files = [
    "LICENSE.txt",
     "README.rdoc"
  ]
  s.files = [
    "CHANGELOG.rdoc",
     "LICENSE.txt",
     "README.rdoc",
     "Rakefile",
     "cubicle.gemspec",
     "cubicle.log",
     "lib/cubicle.rb",
     "lib/cubicle/aggregation.rb",
     "lib/cubicle/calculated_measure.rb",
     "lib/cubicle/data.rb",
     "lib/cubicle/data_level.rb",
     "lib/cubicle/date_time.rb",
     "lib/cubicle/dimension.rb",
     "lib/cubicle/measure.rb",
     "lib/cubicle/member.rb",
     "lib/cubicle/member_list.rb",
     "lib/cubicle/mongo_environment.rb",
     "lib/cubicle/mongo_mapper/aggregate_plugin.rb",
     "lib/cubicle/query.rb",
     "lib/cubicle/ratio.rb",
     "lib/cubicle/support.rb",
     "lib/cubicle/version.rb",
     "test/config/database.yml",
     "test/cubicle/cubicle_aggregation_test.rb",
     "test/cubicle/cubicle_data_level_test.rb",
     "test/cubicle/cubicle_data_test.rb",
     "test/cubicle/cubicle_query_test.rb",
     "test/cubicle/cubicle_test.rb",
     "test/cubicle/mongo_mapper/aggregate_plugin_test.rb",
     "test/cubicles/defect_cubicle.rb",
     "test/log/test.log",
     "test/models/defect.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/PlasticLizard/cubicle}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Pseudo-Multi Dimensional analysis / simplified aggregation for MongoDB in Ruby (NOLAP ;))}
  s.test_files = [
    "test/cubicle/cubicle_aggregation_test.rb",
     "test/cubicle/cubicle_data_level_test.rb",
     "test/cubicle/cubicle_data_test.rb",
     "test/cubicle/cubicle_query_test.rb",
     "test/cubicle/cubicle_test.rb",
     "test/cubicle/mongo_mapper/aggregate_plugin_test.rb",
     "test/cubicles/defect_cubicle.rb",
     "test/models/defect.rb",
     "test/test_helper.rb",
     "examples/cubicles/poker_hand_cubicle.rb",
     "examples/models/poker_hand.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3"])
      s.add_runtime_dependency(%q<mongo>, [">= 0.18.3"])
      s.add_development_dependency(%q<shoulda>, ["= 2.10.3"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.3"])
      s.add_dependency(%q<mongo>, [">= 0.18.3"])
      s.add_dependency(%q<shoulda>, ["= 2.10.3"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 2.3"])
    s.add_dependency(%q<mongo>, [">= 0.18.3"])
    s.add_dependency(%q<shoulda>, ["= 2.10.3"])
  end
end

